### DISCUSSION TITLE
Change checkbox icons and icon color

### DISCUSSION THREAD

**Discussion by emmapaeronpuss** [Akifyss/obsidian-border#138] [Q&A]
Hi! 
- How can I change the icons and the color of the icons in the checkboxes? For example have this one in another color than pink: -[>]. 
- Also, how can I change the text color of the warning text boxes? F.ex. when I want to delete a note, the text is pink and I'd like to change it if possible.
Sorry, am new to all of this!
Thank youuuuuuu :)

**Comment by Akifyss** [comment]
You can add this CSS snippet to change the `color` property to your desired color and the `-webkit-mask-image` property to your desired icon. 

```CSS
input[data-task=">"]:checked,
li[data-task=">"]>input:checked,
li[data-task=">"]>p>input:checked {
    --checkbox-color-hover: var(--color-pink);
    color: var(--color-pink);
    -webkit-mask-image: url('data:image/svg+xml;utf8,<?xml version="1.0" encoding="UTF-8"?><svg id="svg0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><defs><style>.cls-1{fill:none;}</style></defs><rect class="cls-1" width="16" height="16"/><path d="M1.72,1.05c-.08-.04-.18-.06-.27-.05-.09,0-.18,.04-.26,.1-.07,.06-.13,.13-.16,.22-.03,.09-.04,.18-.02,.27l1.4,4.85c.03,.09,.08,.17,.15,.23,.07,.06,.16,.1,.25,.12l5.69,.95c.27,.05,.27,.44,0,.49l-5.69,.95c-.09,.02-.18,.06-.25,.12s-.12,.14-.15,.23l-1.4,4.85c-.02,.09-.01,.19,.02,.27,.03,.09,.09,.16,.16,.22,.07,.06,.16,.09,.26,.1,.09,0,.19,0,.27-.05l13-6.5c.08-.04,.15-.11,.2-.18,.05-.08,.07-.17,.07-.26s-.03-.18-.07-.26c-.05-.08-.12-.14-.2-.18L1.72,1.05Z"/></svg>');
}
```

As for the second point, I don't quite understand. When I delete a note, I don't see any pink text.
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/a1a286d7-ea8e-4813-b9ee-31b2e703bf83)
