### DISCUSSION TITLE
Highlight active paragraph

### DISCUSSION THREAD

**Discussion by Cuadratin** [Akifyss/obsidian-border#154] [General]
Perhaps it's obvious, but I'd like to know hot to highlight active paragraph with the theme. I've seen on screenshots active paragraph highlighted with a grey background color, but I can't get to achieve it.

**Comment by Akifyss** [comment]
Sorry, due to compatibility reasons, this feature has been temporarily removed. You can enable this feature by adding the following code snippet:
```css
.theme-dark {
    --line-active-bg: rgba(255, 255, 255, 0.04);
    --line-active-bg-customize: rgba(255, 255, 255, 0.04);
}

.theme-light {
    --line-active-bg: rgba(0, 0, 0, 0.035);
    --line-active-bg-customize: rgba(0, 0, 0, 0.035);
}

body:not(.line-active-disable) .cm-lineWrapping>.cm-line.cm-active:not(:has(.mk-note-footer, .mk-floweditor-container), .HyperMD-header) {
    background-color: var(--line-active-bg);
    border-radius: var(--radius-s);
}

body:not(.line-active-disable).line-active-bg-color-accent .cm-lineWrapping>.cm-line.cm-active {
    --line-active-bg: hsla(var(--interactive-accent-hsl), 0.08);
}

body:not(.line-active-disable).line-active-bg-color-customize .cm-lineWrapping>.cm-line.cm-active {
    --line-active-bg: var(--line-active-bg-customize);
}

.cm-lineWrapping>.cm-line:not(.HyperMD-codeblock) {
    padding-left: var(--size-4-1);
    padding-right: var(--size-4-1);
}

.cm-lineWrapping>.cm-table-widget .cm-line {
    background-color: unset !important;
    border-radius: unset !important;
    padding-left: unset !important;
    padding-right: unset !important;
}

body:not(.line-active-disable) .markdown-source-view .cm-scroller .cm-line.cm-active.HyperMD-codeblock-bg:not(.HyperMD-codeblock-begin-bg, .HyperMD-codeblock-end-bg) {
    border-radius: 0px;
}

body:not(.line-active-disable) .markdown-source-view .cm-scroller .cm-line.cm-active.HyperMD-codeblock-begin-bg {
    border-bottom-left-radius: 0px;
    border-bottom-right-radius: 0px;
}

body:not(.line-active-disable) .markdown-source-view .cm-scroller .cm-line.cm-active.HyperMD-codeblock-end-bg {
    border-top-left-radius: 0px;
    border-top-right-radius: 0px;
}
```
