### DISCUSSION TITLE
A few questions on external link color, bold text color and command pallet hue.

### DISCUSSION THREAD

**Discussion by StrangeGirlMurph** [Akifyss/obsidian-border#169] [Q&A] [answered]
- How can I make external links follow the accent color just like internal links?
![image](https://github.com/Akifyss/obsidian-border/assets/62220780/722ceb9f-c0cc-45ec-b904-c429504a2cf7)
- Even though the bold text color isn't set bold text is red. How can I change that?
![image](https://github.com/Akifyss/obsidian-border/assets/62220780/ca142c3b-8816-4ca8-a6ea-41f1e8c3bbbb)
- The command pallet and quick switcher are tinted with the accent color. I couldn't find a setting to turn this off. I find it too intense. Is there a way to turn it of?
![image](https://github.com/Akifyss/obsidian-border/assets/62220780/6bb7ce94-3721-45a6-ba49-0b0e186bc48e)

Amazing theme! Thank you all so much <3

**Comment by Akifyss** [comment]
Try importing the following code snippet:

```css
body {
    --link-external-color: var(--text-accent) !important;
    --link-external-color-hover: var(--text-accent-hover) !important;
    --bold-color: inherit !important;
}

body:not(.is-phone) div:has(>input.prompt-input) {
    border-bottom: 1px solid var(--background-modifier-border) !important;
}
```

**Reply by StrangeGirlMurph** [reply]
Do you mean importing in the style settings? That's doesn't work. 
Or do you mean as a global obsidian css snippet?

**Reply by Akifyss** [reply]
The latter, this is a CSS snippet.

**Reply by StrangeGirlMurph** [reply]
This worked for the link and bold text color but not for the search modal tint. It just removed the green line but not the tint.
Thanks for solving the first two but I think this should be something that is configurable with the settings plugin. And that the bold text color setting isn't working might be a bug.

**Reply by Akifyss** [reply]
Sorry, I'm unclear about what you mean by "tint"? I thought it was the accent color line before, but apparently not.
In fact, the first two colors can be manually configured in the style settings, which can be found in the "Editor" section. 
And the bold text color is not a bug, in fact, red is the default color for bold in this theme, and you can adjust the bold color you want through style settings.

**Reply by StrangeGirlMurph** [reply]
With tint I mean the green transparent background color seen in the image. I want it to be the regular dark background color.

Yes the link and bold text colors can be changed using the style settings plugin but you can't set them to be the accent color. That was my point. Also if the default bold text color is red I think that's what should be shown in the settings instead of the transparent: 
![image](https://github.com/Akifyss/obsidian-border/assets/62220780/949ae2e2-0a7a-4b97-9901-ccf8c0d824d0)
I don't the color picker lets you pick transparent anyway.

**Reply by Akifyss** [reply, marked as answer]
Ok I see, you can set its background-color via the following css code：
```css
.prompt {
    background-color: /*input the color you desire here.*/ !important;
}
```
You can set the link and bold text colors to any color through style settings, including the accent color (by entering its color value).
In terms of transparent problems, this is related to the "style settings" plugin. **Style settings will not actively read the current default color**, thus if you do not manually set the color, the picker will show as a transparent color.

**Reply by StrangeGirlMurph** [reply]
This worked thank you.
```css
.prompt {
	background-color: var(--background-primary) !important;
}
```
This doesn't change context menus and file previews though. Not sure what their ID are. A problem with these workarounds is also that they are global. I would love to see those things be changeable for this theme alone.

> You can set the link and bold text colors to any color through style settings, including the accent color (by entering its color value)

Of course. What I was trying to say is that it would be nice if there was at least the option that it could be responsive like other parts of the theme and automatically follow the accent color.
