### DISCUSSION TITLE
Is there a way (maybe css presets) to ungenerate colors (titles, italized, bold, etc.) when export a note on PDF ?

### DISCUSSION THREAD

**Discussion by WesleyKln** [Akifyss/obsidian-border#191] [Q&A]
I love Border theme so much, except the render on PDF.
Titles, italized, bold text, etc. are colored (bold and italized are orange/red) and I don't want this render.
Is there a way to export note on PDF with standard colors ? Grey for italized text, black for bold text, etc.

**Comment by Akifyss** [comment]
You can add the following CSS code snippet to change the color of italicized, bold text
```CSS
.print {
    --bold-color:black;
    --italic-color:gray;
}
```
