### DISCUSSION TITLE
Change the color of hotkey background

### DISCUSSION THREAD

**Discussion by ScribbleGhost** [Akifyss/obsidian-border#200] [Q&A] [answered]
How can I change the color of these red items?

![image](https://github.com/Akifyss/obsidian-border/assets/49068170/08b9f764-d2d4-4b54-a037-eec0bc7eca9d)

**Comment by Akifyss** [comment, marked as answer]
Red color means there are conflicts with your shortcut key settings. Solving the settings conflict is the best way to change the red color. Another way is to import the following css code snippet.
```css
.setting-hotkey.has-conflict{background-color: /*input color here*/;}
```
