### DISCUSSION TITLE
Heading level without hover

### DISCUSSION THREAD

**Discussion by akhavanski** [Akifyss/obsidian-border#236] [Q&A] [answered]
Hello! Thanks for the theme. For me it works perfect. I especially like the heading level showing on hover, how ever I am dreaming of something that would show heading level without the hover. Maybe you could help me with it?

**Comment by Akifyss** [comment, marked as answer]
Try importing this snippet:
```css
.markdown-source-view.mod-cm6 .cm-fold-indicator .collapse-indicator,
:is(.markdown-rendered, .markdown-preview-view) :is(h1,h2,h3,h4,h5,h6) .collapse-indicator{
    opacity: 1;
}
```
