### DISCUSSION TITLE
Font cutting off in menu

### DISCUSSION THREAD

**Discussion by andrew-nielsen-13** [Akifyss/obsidian-border#253] [Q&A]
The font cuts off in the menu on iPhone and iPad with the font size increased in the obsidian settings. This looks fine at default size settings, but it cuts off after font is increased. Unfortunately I have bad vision so I need the font increased. 

This photo is an example of the bottom of 'y' and 'g' and 'p' being cut off. 

I would actually prefer the font a little bigger than this, but this is as small as I can go and still see the titles of folders and notes. Lol. 

![image](https://github.com/Akifyss/obsidian-border/assets/20081158/ed871573-dc33-4ac6-aefd-dbc69eb6a313)

**Comment by Akifyss** [comment]
Try importing this CSS snippet:
```css
.workspace-leaf-content .tree-item-self :is(.tree-item-flair, .tree-item-inner){
    line-height: 1em !important;
}
```
