### DISCUSSION TITLE
请问如何设置能把标题居中？

### DISCUSSION THREAD

**Discussion by JawnSong** [Akifyss/obsidian-border#309] [Q&A]
![1721010968502](https://github.com/user-attachments/assets/26a2ffce-48ef-4c17-b558-16d1a11fb7f3)

**Comment by Akifyss** [comment]
抱歉目前没有这个功能。可以导入这段css代码实现：

```css
.inline-title {
  text-align: center;
}
```
