### DISCUSSION TITLE
Is it possible to disable or hide the "No backlings found" image?

### DISCUSSION THREAD

**Discussion by horacioeps** [Akifyss/obsidian-border#377] [Q&A]
Hi,
Is it possible to disable or hide the "No backlings found" image?
Thanks

**Comment by Akifyss** [comment]
You can import this CSS snippet to disable images:

```css
.tag-pane-empty::before, .bookmarks-pane-empty::before, .pane-empty::before, .search-empty-state::before{
    display: none;
}
```
