### DISCUSSION TITLE
Removing empty state image from search, bookmarks, backlinks etc.

### DISCUSSION THREAD

**Discussion by synapsefire** [Akifyss/obsidian-border#419] [Q&A]
Hi! How can I remove the empty state image from the panels. I'm using snippet below to remove it from search, backlinks and bookmarks but finding something that works for the properties and outline panels proved difficult.
`/* Remove images from empty states in Borders theme */
.search-empty-state::before,
.nav-empty-state::before,
.bookmarks-pane-empty::before {
    display: none !important;
    content: "" !important;
}`

**Comment by Akifyss** [comment]
try this
```css
.tag-pane-empty::before,
.bookmarks-pane-empty::before,
.pane-empty::before,
.search-empty-state::before {
    width: 0px;
    height: 0px;
}
```
