### DISCUSSION TITLE
I have a few questions about customizing

### DISCUSSION THREAD

**Discussion by iHeadway** [Akifyss/obsidian-border#68] [Q&A] [answered]
I'm trying to customize the theme and can't find options in Style Settings for:
- background-color for :hover links
- text-size and color for `code` text
Do I need to add them in my snippet? 
And why are almost all colors shown as transparent in the settings?

**Comment by Akifyss** [comment, marked as answer]
When you do not manually customize the color and save it, the style settings plugin will display the color as transparent as the default. This is a function of the plugin itself.

These options are not currently available, so yes, you will need to manually add the code to your snippet.
- background-color for :hover links:
```css
@media (hover: hover) {

    a:not(.tag, .raindrop-tag, :has(img:not(.link-favicon))):hover,
    .cm-s-obsidian .cm-line:not(.cm-active) span.cm-hmd-internal-link:hover,
    .external-link:not(:has(img:not(.link-favicon))):hover,
    .cm-s-obsidian .cm-line:not(.cm-active) span:is(.cm-link, .cm-url):hover {
        background-color: var(--background-modifier-hover);  /* Your color here */
    }
}
```
- text-size and color for code text:
```css
body {
    --code-size: var(--font-smaller); /* Your text-size here */
    --code-normal: var(--text-muted); /* Your color here */
    --code-comment: var(--text-faint);
    --code-function: var(--color-yellow);
    --code-important: var(--color-orange);
    --code-keyword: var(--color-pink);
    --code-operator: var(--color-red);
    --code-property: var(--color-cyan);
    --code-punctuation: var(--text-muted);
    --code-string: var(--color-green);
    --code-tag: var(--color-red);
    --code-value: var(--color-purple);
}
```
