### ISSUE TITLE
Excalidraw icon

### ISSUE THREAD

**Issue by fchazal** [Akifyss/obsidian-border#113]
Since icons update on the right panel, the Excalidraw icon is no more replaced by the theme icon as it was in the past.

**Comment by Akifyss** [comment]
You can try manually adding the following code snippet to restore the previous Excalidraw icon.
```css
svg.excalidraw-icon {
    background-color: currentColor;
    -webkit-mask-image: url('data:image/svg+xml;utf8,<?xml version="1.0" encoding="UTF-8"?><svg id="a" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.b{fill:none;}</style></defs><rect class="b" width="24" height="24"/><path d="M21.09,9.38c-.08-.2-.21-.38-.36-.53L15.16,3.27c-.15-.15-.33-.28-.54-.37-.4-.17-.85-.17-1.28,0-.2,.09-.38,.21-.52,.36l-1.99,1.98-4.66,1.75c-.27,.1-.51,.27-.69,.5-.18,.22-.31,.49-.36,.78l-1.89,11.34s0,.08,0,.12c0,.02,0,.04,0,.07,0,.11,.02,.22,.06,.32,0,.02,.02,.04,.03,.06,.05,.11,.11,.21,.2,.3,.09,.1,.21,.17,.33,.22,.12,.05,.25,.07,.38,.07,.05,0,.11,0,.16-.01l11.35-1.89c.29-.05,.56-.17,.78-.36,.22-.18,.39-.43,.49-.69l1.75-4.65,1.98-1.98c.16-.16,.28-.34,.36-.54,.08-.2,.13-.42,.13-.64s-.04-.43-.13-.64Zm-5.89,7.56l-8.07,1.34,2.67-2.67c.38,.18,.8,.29,1.25,.29,1.63,0,2.95-1.32,2.95-2.95s-1.32-2.95-2.95-2.95-2.95,1.33-2.95,2.95c0,.45,.11,.87,.29,1.25l-2.67,2.67,1.34-8.07,4.07-1.53,5.6,5.6-1.53,4.07Zm-5.1-3.99c0-.53,.43-.95,.95-.95s.95,.43,.95,.95-.43,.95-.95,.95-.95-.43-.95-.95Zm7.79-1.74l-5.09-5.09,1.19-1.19,5.09,5.09-1.19,1.19Z"/></svg>')
}
```
