### ISSUE TITLE
希望增加代码块行号始终显示的开关

### ISSUE THREAD

**Issue by PupupupuTong** [Akifyss/obsidian-border#125]
长代码仅有跟随鼠标显示不太够用

**Comment by Akifyss** [comment]
可以试试添加以下代码：
```CSS
.workspace-leaf-content[data-type="markdown"] .cm-contentContainer,
.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-codeblock-end {
    counter-reset: code-line;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-codeblock:not(.HyperMD-codeblock-begin):not(.HyperMD-codeblock-end)::after,
.line-hover-indicator .workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-codeblock:not(.HyperMD-codeblock-begin):not(.HyperMD-codeblock-end)::after {
    counter-increment: code-line;
    content: counter(code-line) !important;
    background: unset !important;
    opacity: 1 !important;
    position: absolute !important;
    left: -12px !important;
    top: 0px !important;
    height: 100% !important;
    width: 3px !important;
    display: flex;
    align-items: center;
    justify-content: center;
    white-space: nowrap;
    color: var(--hover-indicator-color);
}
```
