### ISSUE TITLE
Unexpected appearance with Plugin Hider hiding sidebar toggle buttons

### ISSUE THREAD

**Issue by shindgewongxj** [Akifyss/obsidian-border#143]
<img width="1232" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/59656935/ebf142e1-09cd-4841-91dc-cd87a2963dce">

**Comment by Akifyss** [comment]
This issue will be fixed shortly. In the meantime, you can temporarily import the following CSS snippet:
```CSS
.hider-sidebar-buttons.mod-macos .sidebar-toggle-button.mod-left {
    display: unset;
}

.hider-sidebar-buttons.mod-macos .sidebar-toggle-button.mod-left>.clickable-icon{
    display: none;
}
```
