### ISSUE TITLE
CardBoard plugin settings icon is misaligned

### ISSUE THREAD

**Issue by fr3fou** [Akifyss/obsidian-border#144]
Hello, I've been using this theme for the last few months and have been loving it so far. 
I noticed an issue when using the CardBoard plugin – the settings icon is slightly misaligned:

![image](https://github.com/Akifyss/obsidian-border/assets/1344906/fe9dba46-754b-4202-88f6-c04a9c32a2be)

Here is a comparison when using Minimal Theme:

![image](https://github.com/Akifyss/obsidian-border/assets/1344906/a2fed4a3-3976-497d-89b1-f2ec113baba9)

**Comment by Akifyss** [comment]
Try importing the following CSS snippet:
```css
.card-board-view .sidebar-toggle-button {
    padding-top: 6px;
}
```
