### ISSUE TITLE
Active '>' overlaps with blockquote indicator

### ISSUE THREAD

**Issue by batrand** [Akifyss/obsidian-border#166]
When you put the cursor on a blockquote line, for example

```
> some text
```

The blockquote indicator to the left of the blockquote overlaps with the '>'. Screenshot:

![image](https://github.com/Akifyss/obsidian-border/assets/8514709/471f6508-ff39-4a11-8057-8879203fd306)

which I don't think is intentional. Is it possible to move the indicator a bit to the left?

**Comment by Akifyss** [comment]
This issue will be fixed later. For now, you can temporarily resolve this problem by importing the following code snippet:
```css
.cm-s-obsidian span.cm-formatting-quote{
    padding-left: 4px;
}
```
