### ISSUE TITLE
Unexpected Quote Block Style with Code Block Nested

### ISSUE THREAD

**Issue by shindgewongxj** [Akifyss/obsidian-border#184]
**Source Code**:

> [!bug] Nested Code Block
> 
> ```swift
> 	// Without other contents.
> ```
> 

> [!bug] Nested Code Block
> 
> With additional contents before only, the bottom edge looks like:
> 
> ```swift
> 	// Test
> ```
> 

> [!bug] Nested Code Block
> 
> With additional contents before,
> 
> ```swift
> 	// Test
> ```
> 
> and after.
> 

And it will look like:

<img width="728" alt="Screenshot 2024-02-27 at 3 50 08 PM" src="https://github.com/Akifyss/obsidian-border/assets/59656935/a8225143-0083-4859-a963-a7409576b5b6">

**Comment by Akifyss** [comment]
You can import this CSS code to fix it (it feels more appropriate for the official to fix the issue here, so it wasn't included in the theme).

```css
.markdown-rendered .callout-content pre {
    margin: 1em 0px !important;
}
```

**Comment by shindgewongxj** [comment]
Thanks!

Find a [post](https://forum.obsidian.md/t/callouts-not-properly-rendering-spacing-in-live-preview/48569/6) on Obsidian Forum and that works for me:

```css
:root div:not(.cm-callout) > div > .callout {
    margin: 1em 0;
}
```
