### ISSUE TITLE
Howto increase text size of File Explorer ?

### ISSUE THREAD

**Issue by notDavid** [Akifyss/obsidian-border#188]
Hi there,

the text of files and folders in the File Explorer is really small on my iPad.
Is it possible to increase this?
(searched everywhere, can't find it... maybe i'm missing something obvious... ☺️)

Thank you!

**Comment by Akifyss** [comment]
You can import the following CSS snippet to increase the text size of File Explorer
```css
body {
    --nav-item-size: 16px /*replace the font size you want here.*/;
}
```
