### ISSUE TITLE
Incompatibility with obsidian-fullscreen-plugin

### ISSUE THREAD

**Issue by zupodaniel** [Akifyss/obsidian-border#205]
I recently started using obsidian-border and the theme is really cool but after some hours I noticed that it's incompatible with another plugin that I use [obsidian-fullscreen-plugin](https://github.com/Razumihin/obsidian-fullscreen-plugin)

Mixing both plugins results in a solid black background like this:

![Screenshot 2024-03-13 at 14 08 34](https://github.com/Akifyss/obsidian-border/assets/1291373/20f11896-24dd-4eac-8ec5-048c398a7fe1)

**Comment by Akifyss** [comment]
Due to a direct conflict between the theme's functionality and this plugin, this issue is almost impossible to fix, I'm very sorry. 
You can choose to import the following CSS snippet to solve most of the problems:
```CSS
body:not(.is-mobile).is-fullscreen .workspace-tabs:not(.mod-stacked) .workspace-leaf-content {
    background: var(--background-primary) !important;
}
```
