### ISSUE TITLE
Misalingment of Window icons

### ISSUE THREAD

**Issue by Marin-Kitagawa** [Akifyss/obsidian-border#210]
This is a small misalignment. The minimize button is positioned slightly below the center as shown below

![image](https://github.com/Akifyss/obsidian-border/assets/49131888/19536810-8937-4cd7-b274-33b2e9230e99)

As you can see above the minimize button is not exactly aligned with the center of the square next to it.
Not only that the all window controls are actually misaligned from the center as shown below

![image](https://github.com/Akifyss/obsidian-border/assets/49131888/5112db76-f96b-49b6-a535-df631f59ef9f)

The red line denotes the center of the title bar

I haven't developed any theme for Obsidian and hence not sure how to fix this. The `theme.css` file is $8768$ lines long. It'd be better to align the window controls in the vertical center.

But overall, this theme is extremely good.

**Comment by Akifyss** [comment]
Sorry, the minimize button is intentionally designed this way. It's actually a replica of the following image:
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/dbe3ded4-6f18-4bff-bb75-80b5f6fa6bf9)

You can import the following CSS code snippet to align it:
```CSS
.titlebar-button-container.mod-right .titlebar-button.mod-minimize::after {
    -webkit-mask-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='none' viewBox='0 0 16 16'%3e%3cpath stroke='black' stroke-width='2' d='M4 8h8'/%3e%3c/svg%3e");
}
```
