### ISSUE TITLE
vim 模式下Hover

### ISSUE THREAD

**Issue by moooooo16** [Akifyss/obsidian-border#231]
作者你好！

Hover line indicator的设置非常棒，但是vim模式下基本不使用鼠标，能否考虑将vim模式下的Hover 改成光标位置indicator。

望采纳！

谢谢

**Comment by Akifyss** [comment]
可以试一下导入这段css片段：
```css
.workspace-leaf-content[data-type="markdown"] .markdown-source-view .cm-content>.cm-active:not(:has(.mk-note-footer)):has(.cm-hmd-list-indent)::after,
.workspace-leaf-content[data-type="markdown"] .markdown-source-view .cm-content>.cm-active:not(.image-embed, .mk-header, :has(.mk-note-footer, .collapse-indicator))::after {
    content: "";
    position: absolute;
    left: -12px;
    top: 3px;
    width: 3px;
    height: calc(100% - 6px);
    border-radius: 10px;
    background: var(--hover-indicator-color);
    opacity: 1;
}

/* num */
.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line:not(.HyperMD-list-line-1):after,
.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-codeblock:not(.HyperMD-codeblock-begin):not(.HyperMD-codeblock-end)::after {
    background: unset !important;
    opacity: 0 !important;
    position: absolute !important;
    left: -12px !important;
    top: 0px !important;
    height: 100% !important;
    width: 3px !important;
    display: flex;
    align-items: center;
    justify-content: center;
    white-space: nowrap;
    color: var(--hover-indicator-color);
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-active.HyperMD-list-line:not(.HyperMD-list-line-1)::after,
.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-active.HyperMD-codeblock:not(.HyperMD-codeblock-begin):not(.HyperMD-codeblock-end):after {
    opacity: 1 !important;
}

/* code */
.workspace-leaf-content[data-type="markdown"] .cm-contentContainer,
.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-codeblock-end {
    counter-reset: code-line;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-codeblock:not(.HyperMD-codeblock-begin):not(.HyperMD-codeblock-end)::after {
    counter-increment: code-line;
    content: counter(code-line) !important;
}

/* list */
.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line:not(.HyperMD-list-line-1):after {
    content: "";
    text-indent: 0px !important;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line.HyperMD-list-line-2::after {
    content: "2" !important;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line.HyperMD-list-line-3::after {
    content: "3" !important;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line.HyperMD-list-line-4::after {
    content: "4" !important;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line.HyperMD-list-line-5::after {
    content: "5" !important;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line.HyperMD-list-line-6::after {
    content: "6" !important;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line.HyperMD-list-line-7::after {
    content: "7" !important;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line.HyperMD-list-line-8::after {
    content: "8" !important;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line.HyperMD-list-line-9::after {
    content: "9" !important;
}

.workspace-leaf-content[data-type="markdown"] .cm-contentContainer .cm-line.HyperMD-list-line.HyperMD-list-line-10::after {
    content: "10" !important;
}
```
