### ISSUE TITLE
Callout Align and Used alone

### ISSUE THREAD

**Issue by ProudBenzene** [Akifyss/obsidian-border#252]
Dear developer, this theme of yours is really very beautiful, using your theme has made me very happy in using Obsidian, thank you for your dedicated development!

However, I'm having a compatibility issue with it and need to ask you to point me in the right direction.

I have a CSS snippet modified from blue topaz that centers the content of a callout whose metadata contains "center". However, in the Border theme, this centering is not working. My code is as follows:

```css
/* === Support right left center Syntax ============ */
/* Supports two ways of writing
    > [!note|right]
    > [!note right]
   */
.callout.callout:is([data-callout-metadata*="left"],
[data-callout*=left]) {
  float: left !important;
  margin: unset;
}
.callout.callout:is([data-callout-metadata*="right"],
[data-callout*=right]) {
  float: right !important;
  margin: unset;
}

.callout.callout:is([data-callout-metadata*="center"],
[data-callout*=center]) {
  display: block;
  margin: auto;
  float: unset ;
  text-align: center;
}
```

I tried both "|left" and "|right" and both work fine, except "center" which fails. I tried to modify the code to realize this function, but failed. Can you please tell me how to modify the code to realize this function?

Another small requirement I have is that I would like to use a separate callout style for some callouts, while other callouts use the style set in the style setting. I can do this in the AnuPpuccin theme with the callout-metadata function, for example:

```markdown
> [!note|anp-vanilla-normal] Heading
```

It is possible to make that callout alone to be displayed in a style like `anp-vanilla-normal`. I wonder if there is a way for me to do this in the Border theme?

Finally, thank you again for the effort you put into developing such a great theme and I look forward to hearing from you!
