### ISSUE TITLE
Metadata Prettify

### ISSUE THREAD

**Issue by ProudBenzene** [Akifyss/obsidian-border#260]
<img width="462" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/93238080/72161284-c4bb-4b00-8f96-6b2c5e8b271a">

A suggestion, I would like to be able to set up the metadata, especially in List form, to be beautified like the selected properties in Notion. The distinction between List Metadata is too unclear now.

![image](https://github.com/Akifyss/obsidian-border/assets/93238080/dc9b5cf2-fe9e-462e-b67c-731e85b5e9fc)

<img width="210" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/93238080/b914d917-43cf-4804-820b-e0cc157433b3">
<img width="232" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/93238080/4674428a-45a8-4545-a97c-0a0898e8c95a">

Hoping you could take me up on my offer and thank you for your hard work in developing the wonderful theme!

**Comment by Akifyss** [comment]
You can try importing this CSS snippet:
```css
.metadata-property:not([data-property-key="tags"]) .multi-select-pill {
    --pill-padding-x: var(--tag-padding-x);
}

.metadata-property:not([data-property-key="tags"]) .multi-select-pill::after {
    width: 100% !important;
    left: 0 !important;
}

.metadata-property:not([data-property-key="tags"]) .multi-select-pill:nth-child(8n+1) {
    --pill-background: rgba(var(--color-red-rgb), 0.2);
    --pill-background-hover: rgba(var(--color-red-rgb), 0.25);
}

.metadata-property:not([data-property-key="tags"]) .multi-select-pill:nth-child(8n+2) {
    --pill-background: rgba(var(--color-orange-rgb), 0.2);
    --pill-background-hover: rgba(var(--color-orange-rgb), 0.25);
}

.metadata-property:not([data-property-key="tags"]) .multi-select-pill:nth-child(8n+3) {
    --pill-background: rgba(var(--color-yellow-rgb), 0.2);
    --pill-background-hover: rgba(var(--color-yellow-rgb), 0.25);
}

.metadata-property:not([data-property-key="tags"]) .multi-select-pill:nth-child(8n+4) {
    --pill-background: rgba(var(--color-green-rgb), 0.2);
    --pill-background-hover: rgba(var(--color-green-rgb), 0.25);
}

.metadata-property:not([data-property-key="tags"]) .multi-select-pill:nth-child(8n+5) {
    --pill-background: rgba(var(--color-cyan-rgb), 0.2);
    --pill-background-hover: rgba(var(--color-cyan-rgb), 0.25);
}

.metadata-property:not([data-property-key="tags"]) .multi-select-pill:nth-child(8n+6) {
    --pill-background: rgba(var(--color-blue-rgb), 0.2);
    --pill-background-hover: rgba(var(--color-blue-rgb), 0.25);
}

.metadata-property:not([data-property-key="tags"]) .multi-select-pill:nth-child(8n+7) {
    --pill-background: rgba(var(--color-purple-rgb), 0.2);
    --pill-background-hover: rgba(var(--color-purple-rgb), 0.25);
}

.metadata-property:not([data-property-key="tags"]) .multi-select-pill:nth-child(8n+8) {
    --pill-background: rgba(var(--color-pink-rgb), 0.2);
    --pill-background-hover: rgba(var(--color-pink-rgb), 0.25);
}
```
