### ISSUE TITLE
图片的居中对齐主题功能与AttachFlow有冲突

### ISSUE THREAD

**Issue by Ryoga1016** [Akifyss/obsidian-border#263]
https://github.com/Yaozhuwa/AttachFlow/issues/22
现在网络图片还有这个问题，本地图片在前几次更新中莫名修复了。谢谢

**Comment by Akifyss** [comment]
可以先添加这段 css 代码片段：
```css
.img-center-align .print :is(.markdown-preview-view, .markdown-rendered) img:is([class=""],.image-ready-resize),
.img-center-align .markdown-preview-view img:is([class=""],.image-ready-resize),
.img-center-align .markdown-source-view img:is([class=""],.image-ready-resize) {
    display: block;
    margin-left: auto !important;
    margin-right: auto !important;
}
```

**Comment by Ryoga1016** [comment]
还是不能解决这个问题，我暂不用AttachFlow了吧！感谢了

**Comment by Akifyss** [comment]
你试试更新一下主题呢？我试了一下更新后是可以的

**Comment by Ryoga1016** [comment]
早上更新后尝试的，我做了些测试，主要是attachflow的点击图片放大功能和拖拽改变图片尺寸功能都开启的话就会出这个问题，关闭任一功能之后都是正常的了。我做了个gif
![GIF 240508 103244](https://github.com/Akifyss/obsidian-border/assets/49177478/e6690d69-9635-44e9-ad3c-92d02ff4d422)

**Comment by Akifyss** [comment]
之前测试的时候，没有启用点击图片放大功能。试试导入这段代码呢？
```css
.img-center-align .print :is(.markdown-preview-view, .markdown-rendered) img:is([class=""], .image-ready-resize, .image-ready-click-view),
.img-center-align .markdown-preview-view img:is([class=""], .image-ready-resize, .image-ready-click-view),
.img-center-align .markdown-source-view img:is([class=""], .image-ready-resize, .image-ready-click-view) {
    display: block;
    margin-left: auto !important;
    margin-right: auto !important;
}
```
