### ISSUE TITLE
Enhancement Request: Hide icons

### ISSUE THREAD

**Issue by ms3056** [Akifyss/obsidian-border#278]
I've started to make some adjustments to your excellent theme. One I have done is to hide the icons for the workspaces until you hover. It would be a cool addition. 

```css
.workspace-tabs:not(.mod-top) .workspace-tab-header-container .workspace-tab-header-inner-icon,
.workspace-tabs:not(.mod-top) .workspace-tab-header-container .workspace-tab-header-inner::before {
  visibility: hidden;
  transition: visibility 200ms ease-in;
}

/* Show the inner icon on hover */
.workspace-tabs:not(.mod-top) .workspace-tab-header-container:hover .workspace-tab-header-inner-icon,
.workspace-tabs:not(.mod-top) .workspace-tab-header-container:hover .workspace-tab-header-inner::before {
  visibility: visible;
}


/* Hover Style for Workspace Tabs */
.workspace-tabs:not(.mod-top) .workspace-tab-header-container {
  height: 10px;
  transition: height 200ms ease-in;

  &:hover {
    height: var(--header-height);
  }

  &::after {
    content: "";
    display: block;
    width: 100%;
    height: 100%;
    top: 100%;
    position: absolute;
    z-index: 1;
  }
}
```
