### ISSUE TITLE
如何调整标题和正文之间的间距呢

### ISSUE THREAD

**Issue by mahaonanStart** [Akifyss/obsidian-border#305]
阅读模式下标题和正文间距很舒服，但是编辑模式下太过于紧凑。如果手动输入一行，又显得太宽了。问下作者大大，能不能支撑调整编辑模式下标题和正文的间距呢
<img width="715" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/44892851/0a1128cb-a413-46bb-97fb-aa1e472b0def">

**Comment by mahaonanStart** [comment]
还有个问题，手机端如何隐藏上下的菜单栏工具栏呢，感谢赐教

**Comment by Akifyss** [comment]
导入这两段css代码片段应该就能实现：
```CSS
.cm-s-obsidian .cm-line.HyperMD-header{
    padding-bottom: var(--p-spacing);
}
```

```CSS
.is-mobile .view-header,
.is-mobile .mobile-navbar{
    display: none;
}
```
