### ISSUE TITLE
如何调整标题行与正文行的行间距

### ISSUE THREAD

**Issue by Leorinardo** [Akifyss/obsidian-border#310]
在“阅读模式”下，标题行与正文行的行间距很大，详细情况如下，且在编辑模式下，并没有在标题与正文之间插入空行，请问这种情况该如何调整他们之间的行间距呢？望不吝赐教，感谢。
![1](https://github.com/user-attachments/assets/a6e868db-eb1f-47b2-9a7d-a17983d9ff2d)

**Comment by Akifyss** [comment]
可以导入这个css代码片段来调节：
```css
.markdown-rendered h1,
.markdown-rendered h2,
.markdown-rendered h3,
.markdown-rendered h4,
.markdown-rendered h5,
.markdown-rendered h6{
    margin-block-end: 0;
}

.markdown-rendered div:has(h1)+div>p,
.markdown-rendered div:has(h2)+div>p,
.markdown-rendered div:has(h3)+div>p,
.markdown-rendered div:has(h4)+div>p,
.markdown-rendered div:has(h5)+div>p,
.markdown-rendered div:has(h6)+div>p{
    margin-block-start: 0;
}
```
