### ISSUE TITLE
Bug：隐藏库名无效

### ISSUE THREAD

**Issue by KeithW0726** [Akifyss/obsidian-border#326]
我想隐藏下述库名栏，如下图所示：
<img width="687" alt="图片" src="https://github.com/user-attachments/assets/2a0af820-fd55-4be6-b686-f78f5d2a3631">

使用以下CSS

```
body:not(.is-mobile) .workspace-split.mod-left-split .workspace-sidedock-vault-profile {
  display: none;
}
```
经测试，在默认主题和minimal主题均正常生效，但在boarder主题中，则只是对应的文字消失，而所占的空间却没得到释放。
出现了bug

请求修复，也建议可以将此自动隐藏特性加入到border中，毕竟这里十分占空间。

谢谢！

**Comment by Akifyss** [comment]
可以再额外添加这段代码试试：
```css
body:not(.is-mobile) .workspace-split.mod-left-split .workspace-tabs:last-of-type .workspace-tab-container {
    padding-bottom: 0px;
}
```

新版也已经更新自动隐藏，可以试试；
