### ISSUE TITLE
建议对链接下划线与链接文字做一些视觉优化

### ISSUE THREAD

**Issue by i-iooi-i** [Akifyss/obsidian-border#331]
![image](https://github.com/user-attachments/assets/3fef66a2-1fbc-45d0-a06f-d5a7415e2334)
Primary主题：文字链接粗体+暗色下划线

![image](https://github.com/user-attachments/assets/8e63b724-d639-4222-9dc9-218e6979d1b9)
Chime 主题： 文字链接粗体+暗色下划线

![image](https://github.com/user-attachments/assets/3debdd4f-fa46-48e2-bb34-9ddc0584da50)
Border主题：文件链接+下划线

提一个请求：
１　希望大佬考虑增加为链接下划线设置颜色的功能，如上两个主题，当下滑线更暗一些的时候，链接文字与下划线之间，在视觉上会更有层次分明层层递进的效果．现在Border的链接文字与下划线直接使用了相同的颜色，视觉上会更刺眼了．

２　希望大佬考虑一下为链接文字增加粗体的功能开关，这样链接文字与普通文字之间可以在页面内容中做出一些区分，视觉层次感也会更好一些．

感谢大佬的主题，很棒！❤️❤️

**Comment by Akifyss** [comment]
可以导入以下css代码片段来实现这两个功能：
```css
body {
    --link-decoration-color: color-mix(in srgb, var(--link-color) 25%, transparent);
    --link-decoration-color-hover: color-mix(in srgb, var(link-color-hover) 25%, transparent);
}

.internal-link,
.markdown-rendered .internal-link,
.metadata-container .internal-link,
.cm-hmd-internal-link .cm-underline {
    text-decoration-color: var(--link-decoration-color);
    font-weight: bold;
}

.internal-link:hover,
.markdown-rendered .internal-link:hover,
.metadata-container .internal-link:hover,
.cm-hmd-internal-link .cm-underline:hover {
    text-decoration-color: var(--link-decoration-color-hover);
}
```
