### ISSUE TITLE
Compatible Issue in outline with Virtual Link Plugin

### ISSUE THREAD

**Issue by ProudBenzene** [Akifyss/obsidian-border#334]
<img width="838" alt="image" src="https://github.com/user-attachments/assets/6deaf27c-c1fc-41ca-8e60-2ccd9d8f2022">

As shown in the figure, turning on outline optimization in Border creates a conflict with the [Virtual Link plugin](https://github.com/vschroeter/obsidian-virtual-linker), This is evidenced by the fact that phrases with virtual links do not show up properly in the outline.

Could you please adjust the compatibility with this plugin, thanks for your hard work!

**Comment by Akifyss** [comment]
Currently, this mode only supports displaying single-line text. The word in the image is likely too long and has been cut off, which should not be related to the plugin. You can temporarily import this CSS code to display an ellipsis in such cases:
```css
.outline-enhanced .workspace-leaf-content[data-type=outline] .tree-item-inner{
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```
