### ISSUE TITLE
建议：列表缩进设置效果同步及调整；嵌入笔记内容高度限制

### ISSUE THREAD

**Issue by Novice-level** [Akifyss/obsidian-border#335]
当前列表缩进设置后，只对阅读视图起效，但编辑视图未起效。导致视图切换时，列表项有明显的错位感，不知道这个情况能否调整。（个人习惯，调整缩进数值为：1.2em，能使列表与段落文字左侧对齐，更有一体性。）

以及，当前调整缩小了列表缩进后，会导致待办事项在某些情况下，前面的勾选框显示不全。
例：嵌入笔记、dataview的检索结果，但我发现这个情况没有在callout里出现，不知道这个情况能否优化。

最后，如果能设置嵌入笔记内容的高度就好了。

**以上仅为建议，感谢作者。**

**Comment by Akifyss** [comment]
列表和待办事项的问题没能复现到，我这里的设置是能够对编辑模式生效的，你可以在沙盒环境中再试一下吗？猜测可能是某些插件影响？
![image](https://github.com/user-attachments/assets/2adc8f67-0a34-4be5-995c-4eec9055b3aa)

---

关于嵌入笔记内容的高度，可以暂时导入这段css代码自行调节里面的值（之后这个功能应该也会更新到主题）：
```CSS
body{
    --embed-max-height: 4000px;
}
```

**Comment by Novice-level** [comment]
感谢作者的回复，我这边重新尝试了，但列表缩进的问题仍然存在，而且callout内也存在问题了。请看截图
（当前问题并不影响编辑，仅从美观角度来看有所不足，这只是一个建议，以作者意愿决定。感谢作者。）
![image](https://github.com/user-attachments/assets/bb352b3a-0948-4553-a882-cccca2294c79)
![image](https://github.com/user-attachments/assets/bfeaf5bc-431a-462c-8ffb-87d02e1bf887)
![image](https://github.com/user-attachments/assets/ce33a467-1d13-45e5-aa94-ceaeac859dda)

**Comment by Akifyss** [comment]
这个问题和style-setting里的list-indent这个参数应该是没什么关系的，错位的问题应该是官方故意这么写的（原因不得而知），编辑模式多出来的一部分，初步看来是由于官方css文件中的  --list-indent-editing: 0.75em;
![image](https://github.com/user-attachments/assets/5b4a89a5-0321-435b-b9eb-a9c857a30a42)

要想移除编辑模式多出来部分，可以将list-indent-editing改成0（这也是ITS 的做法）。可以导入这段css代码：

```css
body{
    --list-indent-editing: 0;
    --indentation-guide-editing-indent:0.25em;
}

.HyperMD-task-line{
    --indentation-guide-editing-indent:0.85em;
}
```
---

至于待办事项被裁，原因是因为1.2em太小了，过小的空间把checkbox挤出了callout和内嵌的容器可视范围之外，如果不改动1.2em的话，可以导入这行css代码：
```css
.callout-content {
    overflow-x: visible ;
}
.inline-embed .markdown-embed-content,
.inline-embed .markdown-embed-content .markdown-preview-view{
    overflow: visible ;
}
```
