### ISSUE TITLE
能否增加引用块和标题前面竖线的开关？

### ISSUE THREAD

**Issue by jiangaq** [Akifyss/obsidian-border#341]
🙏

**Comment by Akifyss** [comment]
引用块的竖线可以通过这导入个代码段来隐藏：
```css
body{
    --blockquote-border-color: transparent;
}
```
---
标题前面竖线的开关在这个位置：
![image](https://github.com/user-attachments/assets/86979814-971b-4def-b4f5-3b94692b3cf4)
