### ISSUE TITLE
请问如何隐藏高亮背景色？

### ISSUE THREAD

**Issue by i-iooi-i** [Akifyss/obsidian-border#342]
https://github.com/user-attachments/assets/2dec70c5-cb0a-4602-8ff9-119db75a431b

打扰老板们，请问如何隐藏高亮背景色呢？在设置里好像没有找到开关~

主要是白色的背景，没有必要高亮显示~
另外每次鼠标经过链接都会闪烁一下，还是不太习惯这种方式。🙈

**Comment by Akifyss** [comment]
可以导入这行css代码：
```css
body{
    --link-color-hover: hsl(from var(--link-color) h s calc(l - .1) / 100%);
}

a:not(.tag, .raindrop-tag, .clickable-icon, :has(img:not(.link-favicon))):hover,
.cm-s-obsidian .cm-line:not(.cm-active) span.cm-hmd-internal-link:hover,
.external-link:not(:has(img:not(.link-favicon))):hover,
.cm-s-obsidian .cm-line:not(.cm-active) span:is(.cm-link, .cm-url):hover {
    background-color: transparent;
}
```
