### ISSUE TITLE
Shift + scroll in Stacked tabs doesn't work

### ISSUE THREAD

**Issue by Kayfum** [Akifyss/obsidian-border#345]
Hi,
Fantastic theme!
I find that when I try to move between tabs with Shift + scroll in stacked tabs doesn't work.
Any reason for that?
How could I make it work?
Thanks in advance!

**Comment by Akifyss** [comment]
Try adding this code snippet to see if it helps：

```CSS
body:not(.is-mobile).card-layout-open-light.theme-light .workspace-tabs.mod-stacked .workspace-tab-container,
body:not(.is-mobile).card-layout-open-dark.theme-dark .workspace-tabs.mod-stacked .workspace-tab-container {
    overflow-x: auto!important;
}
```

Detailed information can be found in this issue: https://github.com/Akifyss/obsidian-border/issues/47
