### ISSUE TITLE
能不能增加个对callout的文本大小的调整选项？

### ISSUE THREAD

**Issue by jiangaq** [Akifyss/obsidian-border#346]
因为觉得比正文小一号好看些

谢谢 节日快乐！

**Comment by Akifyss** [comment]
可以试试导入这段css代码：

```css
body{
    --callout-title-size:14px;
    --callout-content-size:14px;
}

.callout-content{
    font-size: var(--callout-content-size);
}
```
