### ISSUE TITLE
用Highlightr插件时，高亮的上半部分没有变透明

### ISSUE THREAD

**Issue by jiangaq** [Akifyss/obsidian-border#348]
当我用Blue Topaz时，用Highlightr高亮文字时，只有文字的下面会被划上高亮的粗线，上半部分是透明的，border中是上半部分也有浅色的高亮，能否修复下
Blue Topaz:
<img width="149" alt="image" src="https://github.com/user-attachments/assets/402a2067-b8fd-40d3-8546-ab463d7c9e12">

Border:
<img width="122" alt="image" src="https://github.com/user-attachments/assets/eddfba04-dec6-410a-90a0-45db3ab94bf0">

**Comment by Akifyss** [comment]
抱歉，我无法从图中准确判断问题所在。主要是不清楚您提到的【上半部分】具体指什么，因为从图片上看，高亮区域都出现在文本下方，只是颜色有所不同。我也在自己的环境中进行了测试，目前没有发现【浅色的高亮】问题。所以，能否请您再详细描述一下？

![image](https://github.com/user-attachments/assets/4298f2ca-3041-4ddc-a088-675bbd745b3d)

**Comment by jiangaq** [comment]
我可能没表达清楚，就是高亮的文字的背景色和页面背景色不一致

<img width="186" alt="image" src="https://github.com/user-attachments/assets/8ca2e3d3-9da1-4ffb-851b-e08838fb91a1">
<img width="192" alt="image" src="https://github.com/user-attachments/assets/5fcb07ac-03b7-4e54-aa28-0e2a6a4fab2a">

**Comment by Akifyss** [comment]
你可以在沙盒环境中试试吗，我的是正常的；应该是有什么插件冲突了吧

**Comment by jiangaq** [comment]
我看了下，是style里的设置问题：

![CleanShot 2024-10-06 at 19 48 39@2x](https://github.com/user-attachments/assets/953cd29a-47fd-43a4-b123-2f7481486154)
![CleanShot 2024-10-06 at 19 48 58@2x](https://github.com/user-attachments/assets/12de97da-bb54-49bd-90b1-ac1ef4952da4)
设了这2个就出现问题了

**Comment by Akifyss** [comment]
导入这行代码应该可以解决：
```css
.highlightr-floating mark, .highlightr-floating span.cm-highlight, .highlightr-floating .markdown-preview-view mark{
    --floating-background:#ffffff;
}
```
