### ISSUE TITLE
Issue #123 has resurfaced

### ISSUE THREAD

**Issue by spiritualgeek** [Akifyss/obsidian-border#351]
Please check #123

**Comment by Akifyss** [comment]
Could you please provide any images? I'm not sure about the location of the arrows of the pane relief plugin. 
Sorry, I'm not a user of this plugin and am unfamiliar with its specific features.

**Comment by spiritualgeek** [comment]
<img width="120" alt="image" src="https://github.com/user-attachments/assets/ef691266-25ad-4720-89f3-307f64715262">

**Comment by Akifyss** [comment]
I can't reproduce the issue. Could you test it again in a sandbox environment? I suspect there might be interference from other plugins.
![image](https://github.com/user-attachments/assets/196f444e-ad1b-4df8-a790-089aebce75b0)

**Comment by spiritualgeek** [comment]
It seems to be happening intermittently

<img width="68" alt="image" src="https://github.com/user-attachments/assets/496e4c00-0ff4-4386-950e-97e53925e2a4">

This is from 2 notes I have open at the moment. On the 1 note it displays without an inssue

**Comment by Akifyss** [comment]
I did a brief check, and the theme updates during this period shouldn't involve this part; since it occurs intermittently, I personally speculate that the issue is likely unrelated to the CSS theme. I also don't know the cause of the problem and am currently unable to help resolve it. Sorry about that.

**Comment by spiritualgeek** [comment]
Hi @Akifyss 

I think that I located the issue:
```css
.clickable-icon.document-search-button,
.clickable-icon.document-search-close-button,
body:not(.is-mobile) .workspace-split.mod-left-split .workspace-sidedock-vault-profile .workspace-drawer-vault-actions .clickable-icon,
.mod-left-split .workspace-tab-header .workspace-tab-header-inner,
.mod-right-split .workspace-tab-header .workspace-tab-header-inner,
.clickable-icon.nav-action-button,
.clickable-icon.side-dock-ribbon-action,
.sidebar-toggle-button .clickable-icon,
.workspace-tab-header-new-tab .clickable-icon,
.workspace-tab-header-tab-list .clickable-icon,
.view-header .clickable-icon {
    padding: unset;
    height: unset;
    width: unset;
}
```

I just did an unset on all 3, and it fixes the issue

Note the sizing after I put this in a snippet:
<img width="154" alt="image" src="https://github.com/user-attachments/assets/238d6652-6907-413f-9221-606c9c9c371d">

It only seems to happen in the right tab group
