### ISSUE TITLE
Minimize button is not centered on Obsidian ribbon

### ISSUE THREAD

**Issue by mydkm** [Akifyss/obsidian-border#357]
Hi, hope you're doing well. 

For some reason, my minimize button is not centered on my ribbon (as shown in the attached image). Not a large issue, just wondering if you could help me resolve it.

Thank you and have a good day.

![Screenshot 2024-10-19 145020](https://github.com/user-attachments/assets/4422418e-83da-470b-b2eb-24b9d24a2a4b)

**Comment by Akifyss** [comment]
You can import the following CSS code snippet to align it:
More details can be found at: #210

```css
.titlebar-button-container.mod-right .titlebar-button.mod-minimize::after {
    -webkit-mask-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='none' viewBox='0 0 16 16'%3e%3cpath stroke='black' stroke-width='2' d='M4 8h8'/%3e%3c/svg%3e");
}
```
