### ISSUE TITLE
Buttons in Kanban are hard to read in Light Mode.

### ISSUE THREAD

**Issue by DudeThatsErin** [Akifyss/obsidian-border#416]
I have a picture:
![image](https://github.com/user-attachments/assets/2044115c-8e3f-4dbc-9c35-2a02a454fd8f)

This is on my ipad and iphone. Latest version of theme and obsidian (1.8.9)

**Comment by Akifyss** [comment]
I've noticed this issue exists in other themes as well. The best solution should come from a fix within the Kanban plugin. However, you can import this CSS snippet as a temporary workaround.

```css
.kanban-plugin__new-item-button:hover {
    color: var(--text-on-accent) !important;
    background-color: var(--interactive-accent-hover) !important;
}
```
