### ISSUE TITLE
Nonscrollable Sliding Panes/Stacked Tabs & right Stacked Tab-Note gets covered by Sidepane

### ISSUE THREAD

**Issue by SwoleNugget** [Akifyss/obsidian-border#417]
The Stacked Tabs or Panes cannot be sidescrolled with my sideways mousewheel (Logitech MX Master 3). At least not for me. This functions well in the Obsidian Default Theme or any other theme. I also haven't found any Setting so far that would enable or disable this through the Style Settings.

Problems with opening right stacked Tab fully which gets covered half way when right sidepane is opened (15" Laptop). When I try opening it by clicking on it, I cant see half of the Note. Only if I start writing the page widens up all naturally when the cursor moves to the right.

**Comment by Akifyss** [comment]
Try adding this code snippet to see if it helps：

```css
body:not(.is-mobile).card-layout-open-light.theme-light .workspace-tabs.mod-stacked .workspace-tab-container,
body:not(.is-mobile).card-layout-open-dark.theme-dark .workspace-tabs.mod-stacked .workspace-tab-container {
    overflow-x: auto!important;
}
```

Detailed information can be found in this issue: https://github.com/Akifyss/obsidian-border/issues/47

---

The second issue can be reproduced in other themes, and I suspect it's an Obsidian issue, which CSS themes probably can't fix. It should be reported to the official Obsidian team.
