### ISSUE TITLE
请教一下样式设置问题

### ISSUE THREAD

**Issue by EternalZeus** [Akifyss/obsidian-border#422]
您好，请问在border主题下如何修改选中文本后的高亮颜色呢？我在style settings中似乎并没有找到相关选项。

<img width="167" alt="Image" src="https://github.com/user-attachments/assets/c9835390-0cb6-4be5-93f2-269da072d1a7" />

**Comment by Akifyss** [comment]
应该是这个位置
![Image](https://github.com/user-attachments/assets/f5aba7de-4db7-4e09-9ecb-d2748f0d4440)

**Comment by EternalZeus** [comment]
抱歉，我表述的不是很清楚。不是进行高亮文本操作时的颜色，而是用鼠标长按拖动选中了一段文本后显示的颜色

**Comment by Akifyss** [comment]
可以导入这段css 片段来解决

```css
.cm-s-obsidian span.cm-formatting-highlight,
.cm-s-obsidian span.cm-highlight,
.markdown-rendered mark {
    color: #ffffff; /* #修改此处的色值 */
}
```
