### ISSUE TITLE
Titlebar buttons bug for tab-bar auto-hide

### ISSUE THREAD

**Issue by MysterV** [Akifyss/obsidian-border#450]
The titlebar (minimize, maximize, close) buttons extend below the topbar, like the rest of the topbar buttons, but unlike the rest, hovering over them triggers the topbar to unhide, which is annoying when you just want to access the tab menu.

![Current behavior](https://github.com/user-attachments/assets/e152919e-84ce-41ed-8cfb-781b965ee09b)

I hacked together a quick-fix solution, which works, it's not perfect, but it might serve as a starting point.
I couldn't figure out how to make the titlebar buttons not get squeezed when hiding like the rest of the top bar buttons that just fade away.

![My quick fix](https://github.com/user-attachments/assets/5975ab13-f73c-481d-8b82-9ad1a511dfa1)

```css
body:not(.is-mobile).tab-autohide.is-hidden-frameless .titlebar-button {
    height: 100%;
}

body:not(.is-mobile).tab-autohide:has(.mod-top>.workspace-tab-header-container:hover, .titlebar-button-container:hover) .titlebar-button {
    height: 44px;
}
```
