### ISSUE TITLE
Enabling Card Layout breaks horizontal scrolling for stacked tabs

### ISSUE THREAD

**Issue by ggstrader** [Akifyss/obsidian-border#47]
Title says it all

**Comment by Akifyss** [comment]
You can choose to manually import this CSS snippet to restore the scrollbar, but the rounded corners at the bottom of the card will disappear. This is a problem that cannot be solved perfectly😞

```css
body:not(.is-mobile).card-layout-open-light.theme-light .workspace-tabs.mod-stacked .workspace-tab-container,
body:not(.is-mobile).card-layout-open-dark.theme-dark .workspace-tabs.mod-stacked .workspace-tab-container {
    overflow-x: auto!important;
}
```
