### ISSUE TITLE
Feature Request: option to render Explorer buttons and Tab Title as bars

### ISSUE THREAD

**Issue by batrand** [Akifyss/obsidian-border#56]
Hey there! Sorry that I keep making these requests but Border has been my main theme for the past few weeks and I'm loving it! One thing that keeps bothering me is that the top buttons bar in the Explorer pane and the tab title bars look like this:
![image](https://user-images.githubusercontent.com/8514709/227813598-b3db9428-7065-4807-9427-eb12f051e6b8.png)

Like how content scrolls underneath it and it's obvious that they're UI elements above the content, but there's no divider to clearly show that they're, well, bars.

I tried to hack together some CSS 
```css
div .nav-buttons-container {
    border-bottom: 1px dashed var(--background-modifier-border)!important;
}

div .view-header-title-container {
    border-bottom: 1px dashed var(--background-modifier-border)!important;
}
```
But it doesn't look good :( 
![image](https://user-images.githubusercontent.com/8514709/227813829-25ec540c-68db-4c0b-b73a-06792344b9b9.png)

Especially if I want to turn on the big Note button:
![image](https://user-images.githubusercontent.com/8514709/227813881-0b11d587-7bd8-4ed3-8f72-1c2eafd8f2f6.png)

I also tried to make the bars for the tab title bar extend across the entire pane, but then the right pane's buttons clip into the divider and just doesn't look nice:
![image](https://user-images.githubusercontent.com/8514709/227814239-804450d0-409b-4802-9c8f-01a5297e4fe1.png)

At this point I'm at the extent of my CSS hackability so I thought that I should ask if you'd consider adding an option to render them more clearly as bars, but actually make it pretty and fit in with the rest of the theme haha.

**Comment by Akifyss** [comment]
Try this code snippet:

```CSS 
.view-header,
.nav-header {
    --header-height: 48px;
    border-bottom: 1px dashed var(--background-modifier-border);
}
```
