### ISSUE TITLE
Improvement: Vault name with more visibility

### ISSUE THREAD

**Issue by JigenDD** [Akifyss/obsidian-border#67]
Lately, since my notes have grown, I have divided them between 3 different vaults. Border is immensely helpful for this, as slightly different colors between vaults (i.e. each vault having Border have differentiated background colors and gradients) help me distinguish between them better. But sometimes it is not enough for my working memory and attention span (especially after a few hours of work), and I have to go look up the vault's name. 

Now this is where I find a minor (but relevant) inconvenience: The vault name is hard to read. 

The vault name is neatly tucked in the upper part of the folder navigation tab, and if it is long (like mine are) you have to scroll all the way up to find it. But the fond is the same size and color as the font that is found in the file navigation, which makes it hard to see when all you want is a quick confirmation of which vault you're using. 

These are a number of suggestions I'd have to improve the usability without compromising the design. Implementing 1 or 2 of these, (or as many as you'd see fit) would be a massive help.

- Center the vault name in the left pane.
- Make the vault name have a customizable bigger font by default, and a customizable font color.
- Make the vault name have a sounded pill-like border around with rounded corners (to fit the design language of the overall theme)  with customizable background color.
- Make the vault name have an optional emoji-like icon before it, to its left.
- Have the possibility of adding a short small animation _(like a vibration, or flowing colors -- possible in css to my knowledge)_ every time the vault name comes into view.

**Comment by Akifyss** [comment]
The following code may be helpful for you：
```css
.workspace-leaf-content[data-type="file-explorer"] .nav-folder.mod-root>.nav-folder-title {
    width: calc(100% - 24px);
    display: flex;
    justify-content: center;
    font-size: 16px;/*your font size*/
    --nav-item-color: red;/*your font color*/
}
```
You can also try enabling the "fix vault name position" style settings option.
