### ISSUE TITLE
Stack Tabs not working properly with theme.

### ISSUE THREAD

**Issue by hanconel** [Akifyss/obsidian-border#77]
Stack Tabs (previously sliding panes) does not work when I `shift + scroll`. I have to manually click on each tab after they are "stacked". It works fine in the default appearance.

**Comment by hanconel** [comment]
The problem seems to occur after I "Enable card layout" in the Style setting plugin.

**Comment by Akifyss** [comment]
Try adding this code snippet to see if it helps：
```css
body:not(.is-mobile).card-layout-open-light.theme-light .workspace-tabs.mod-stacked .workspace-tab-container,
body:not(.is-mobile).card-layout-open-dark.theme-dark .workspace-tabs.mod-stacked .workspace-tab-container {
    overflow-x: auto!important;
}
```
Detailed information can be found in this issue: https://github.com/Akifyss/obsidian-border/issues/47
