### ISSUE TITLE
Horizontal mouse side scrolling not working w/ card layout + stacked tabs

### ISSUE THREAD

**Issue by simonayotte** [Akifyss/obsidian-border#85]
Horizontal mouse side scrolling (from left to right) is **not working** with the card layout enabled and stacked tabs. This makes it impossible to scroll through your open notes with the horizontal mouse scroll wheel.

Using most recent installer version (v. 1.3.5) on macOS Venture 13.0

**Comment by evanlauerbsu** [comment]
@Akifyss I fixed it!

```css
body:not(.is-mobile).card-layout-open-light.theme-light .workspace-tabs.mod-stacked .workspace-tab-container,
body:not(.is-mobile).card-layout-open-dark.theme-dark .workspace-tabs.mod-stacked .workspace-tab-container {
  overflow-x: auto!important;

  &::-webkit-scrollbar {
    display: none;
  }
}:
```

**Comment by Evthestrike** [comment]
Hiding the track only still allows you to see the scrollbar
```css
body:not(.is-mobile).card-layout-open-light.theme-light .workspace-tabs.mod-stacked .workspace-tab-container,
body:not(.is-mobile).card-layout-open-dark.theme-dark .workspace-tabs.mod-stacked .workspace-tab-container {
  overflow-x: auto!important;

  &::-webkit-scrollbar-track {
    display: none;
  }
}:
```

**Comment by Evthestrike** [comment]
I'm annoying, 1 last edit. This adds a small "margin" to the sides of the scrollbar to make it look nicer

```css
body:not(.is-mobile).card-layout-open-light.theme-light .workspace-tabs.mod-stacked .workspace-tab-container,
body:not(.is-mobile).card-layout-open-dark.theme-dark .workspace-tabs.mod-stacked .workspace-tab-container {
  overflow-x: auto !important;

  &::-webkit-scrollbar-button {
    width: 2px !important;
  }

  &::-webkit-scrollbar-track {
    display: none;
  }
}
```
