### ISSUE TITLE
File icons separate removal

### ISSUE THREAD

**Issue by Verssgn** [Akifyss/obsidian-border#86]
Any way to remove the file icon while keeping the folder icons? Thanks

**Comment by Akifyss** [comment]
Try adding this code snippet to see if it helps：

```css
.workspace-leaf-content[data-type="file-explorer"] .nav-file-title .nav-file-title-content::before {
    background-color: transparent;
}
```
